### PR TITLE
Feature/sessions endpoint

### PR DESCRIPTION
**Pull request by yash1337**
FInal PR!

### CODE REVIEW

**Comment by nathankurt** [comment]
This pull request **introduces 10 alerts** and **fixes 1** when merging 277d6eed05d19919e21182855b82cb9b2b411a8d into 6755a9959b8e60dacb84e50e8babb5510f9dd765 - [view on LGTM.com](https://lgtm.com/projects/g/SpartaHack/SpartaHack_API_2019/rev/pr-afe820fb659dfc53122ba97ceb3e5c012f6e3d0b)

**new alerts:**

* 10 for Unused import

**fixed alerts:**

* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by nathankurt** [comment]
This pull request **introduces 10 alerts** and **fixes 1** when merging d80d97f07d2af97bcc448815b0622095b2ae6728 into 6755a9959b8e60dacb84e50e8babb5510f9dd765 - [view on LGTM.com](https://lgtm.com/projects/g/SpartaHack/SpartaHack_API_2019/rev/pr-e75fada4a7d55317b5c891f88c8066a82329b382)

**new alerts:**

* 10 for Unused import

**fixed alerts:**

* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by nathankurt** [comment]
This pull request **introduces 9 alerts** and **fixes 2** when merging 084e2e2975bdeccd73ea2792b94dd72a2e6664c2 into 6755a9959b8e60dacb84e50e8babb5510f9dd765 - [view on LGTM.com](https://lgtm.com/projects/g/SpartaHack/SpartaHack_API_2019/rev/pr-72ebd0b9cb87a20c04f5c099116a70493b1e2feb)

**new alerts:**

* 9 for Unused import

**fixed alerts:**

* 1 for Unused local variable
* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by nathankurt** [comment]
This pull request **introduces 9 alerts** and **fixes 2** when merging d5c41ac7afe00de8e3f3cd64ea07fe1cbf94150e into 6755a9959b8e60dacb84e50e8babb5510f9dd765 - [view on LGTM.com](https://lgtm.com/projects/g/SpartaHack/SpartaHack_API_2019/rev/pr-eb0d72af01ff20975cc11503dcdc49a788ae3a3c)

**new alerts:**

* 9 for Unused import

**fixed alerts:**

* 1 for Unused local variable
* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by nathankurt** [comment]
This pull request **introduces 10 alerts** and **fixes 2** when merging 44812a56c7e68957f3a5227da35cdcee6d877384 into 6755a9959b8e60dacb84e50e8babb5510f9dd765 - [view on LGTM.com](https://lgtm.com/projects/g/SpartaHack/SpartaHack_API_2019/rev/pr-6635aebffd95002f0a781ee005f9f1ff4311a3dd)

**new alerts:**

* 10 for Unused import

**fixed alerts:**

* 1 for Unused local variable
* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by yash1337** [comment]
I have spent more time on fixing travis than on writing the API. The PR is good to go. I have used the same postman tests on my machine and they all pass perfectly.

**Comment by nathankurt** [comment]
This pull request **introduces 10 alerts** and **fixes 2** when merging a2aae82d77186ce7e005c6205b52be08d7fd8b29 into 6755a9959b8e60dacb84e50e8babb5510f9dd765 - [view on LGTM.com](https://lgtm.com/projects/g/SpartaHack/SpartaHack_API_2019/rev/pr-efc516821005f2efc42ca5b34f170a959f3d8792)

**new alerts:**

* 10 for Unused import

**fixed alerts:**

* 1 for Unused local variable
* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
